# Generated by Django 3.2.15 on 2022-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='t_date',
            field=models.DateField(default='1999-03-11'),
            preserve_default=False,
        ),
    ]
